/* ============================================
   LEAN APP — Language Data (EN / SV)
   ============================================ */

window.LEAN_TRANSLATIONS = {
  en: {
    nav_lang_label: "Svenska", // label shown offers the OTHER language
    nav_rsv: "RSV",
    nav_why: "Why Lean",
    nav_features: "Features",
    nav_pricing: "Pricing",
    nav_about: "About Us",
    nav_support: "Get Support",

    hero_tag: "Available on iOS & Android",
    hero_h1_1: "Transform",
    hero_h1_2: "Every",
    hero_h1_3: "Process.",
    hero_p: "Walk through process components and unravel inefficiencies fully. Observe, capture, and improve — value-flow's LEAN APP puts powerful process intelligence in your hands.",
    hero_btn_apple: "App Store",
    hero_btn_google: "Google Play",
    stat_modules: "Modules",
    stat_platform: "Platform",
    stat_founded: "Founded",

    observe_tag: "Methodology",
    observe_h2_1: "Observe and",
    observe_h2_2: "Capture",
    observe_p: "Walk through the various components and unravel the process fully. Know the hidden elements of the process that are usually taken for granted despite suffering the excruciating process pain.",
    observe_sub: "Learn and look for the",
    feat1: "VALUE added moments in a process",
    feat2: "What stalls the continuation of an activity",
    feat3: "Choking situations in the free flow of the process",
    feat4: "Are the activities spread out seamlessly",
    feat5: "The discrete situations",
    feat6: "Easy to capture unsafe moments",
    feat7: "Unbiased process capture through comparisons",
    feat8: "Historical process shift observation",

    devices_tag: "Cross-Platform",
    devices_h2_1: "Available on all",
    devices_h2_2: "Your Devices",
    devices_p1: "Wherever you go, the lean apps in your hands can make you shape up the fabric nature of the process by truly observing and highlighting it — with visuals, audios, and video grabbing, all in your hand.",
    devices_p2: "Define the strength of your assembly or business process by detailed analysis right at your hand and work on corrective steps.",
    devices_p3: "PROJECT helps to connect all the members and gives the status completion anywhere, anytime. Status updates simultaneously at all places. No need for meetings or follow-ups —",
    devices_p3_em: " You do, you say, you are seen.",

    rsv_tag: "Right Simple Visuals",
    rsv_h2: "Words are always good.",
    rsv_p: "Alternatively, the Right Simple Visuals (RSV) make an impact on the mind. This will help and surely trigger a Response from the user for every module. The visuals connect the process reality in front of the eyes.",

    why_tag: "Methodology",
    why_h2: "Why",
    why_p: "Lean thinking transforms the way your business operates — eliminating waste and focusing on what truly adds value.",
    why_btn: "Watch: Why Lean Matters",

    feat_tag: "What's Inside",
    feat_h2_1: "Features In",
    feat_h2_2: "This App",
    feat_desc: "As a project lead for every collaborative work big or small, empower and enable people to work in a Team environment using the PROJECT Module.",
    card1_title: "Free Trial",
    card1_p: "Start with zero cost. Explore all core features for 30 days before committing.",
    card2_title: "Custom Modules",
    card2_p: "Tailor the app's modules to match your specific industry and workflow needs.",
    card3_title: "Projects",
    card3_p: "Connect all team members with real-time status updates from anywhere, anytime.",
    card4_title: "Fast Support",
    card4_p: "Get prompt expert assistance whenever you need guidance on the platform.",

    pricing_tag: "Plans",
    pricing_h2_1: "Move Ahead with",
    pricing_h2_2: "Hands On",
    pricing_p: "Choose the plan that fits your observation and analysis needs.",
    plan_free: "Lean Free",
    period_trial: "/ 30 days trial",
    feat_img: "Image capture",
    feat_vid: "Video capture",
    feat_extvid: "Extended video capture",
    feat_va: "Value added activity",
    feat_nva: "Non Value added activity",
    feat_ova: "Operational value activity",
    feat_unsafe: "Unsafe Observation",
    feat_user: "User section",
    feat_compare: "Compare",
    feat_projects: "Projects",
    plan_silver: "Lean Silver",
    period_30: "/ 30 days",
    plan_gold: "Lean Gold",
    period_60: "/ 60 days",
    plan_popular: "Popular",
    plan_platinum: "Lean Platinum",
    period_90: "/ 90 days",
    plan_monthly: "Lean Monthly",
    period_monthly: "/ monthly",

    about_tag: "Who We Are",
    about_h2_1: "About",
    about_h2_2: "Us",
    about_p: "Value-flow Sweden is a consultancy company that develops apps for a more efficient industry, where our mission is that our customers should see their opportunities to improve. Founded in 2017, the company has since been working to achieve higher efficiency, safer production and more equality in industry.",
    about_quote: "\"Contrary to what many consulting companies do, we do not want to talk about what you should do, but instead we want to help you do this. We are working on developing apps that use modern technology to help our customers achieve their goals.\"",

    contact_tag: "Support",
    contact_h2_1: "Looking For",
    contact_h2_2: "Support?",
    contact_p: "Got a question? We'd love to hear from you. Send us a message and we will respond as soon as possible.",
    contact_email_label: "Email Us",
    contact_web_label: "Website",
    contact_loc_label: "Location",
    form_name: "Your Name *",
    form_email: "Email Address *",
    form_phone: "Phone Number",
    form_company: "Company",
    form_subject: "This question is about...",
    form_opt0: "Select a topic",
    form_opt1: "Registering / Authorising",
    form_opt2: "Using Application",
    form_opt3: "Other",
    form_msg_label: "Your Message *",
    form_submit: "Send Your Message",

    news_h3: "Stay up to date with our news, ideas and updates",
    news_btn: "Subscribe",

    footer_desc: "Lean Apps walks through process components & transforms them to efficient process.",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Use",
    footer_copy: "© 2018 value-flow.se — All Rights Reserved"
  },

  sv: {
    nav_lang_label: "English",
    nav_rsv: "RSV",
    nav_why: "Varför Lean",
    nav_features: "Funktioner",
    nav_pricing: "Priser",
    nav_about: "Om Oss",
    nav_support: "Få Support",

    hero_tag: "Tillgänglig på iOS & Android",
    hero_h1_1: "Transformera",
    hero_h1_2: "Varje",
    hero_h1_3: "Process.",
    hero_p: "Gå igenom processkomponenter och avslöja ineffektivitet fullt ut. Observera, fånga och förbättra — value-flows LEAN APP ger kraftfull processintelligens i din hand.",
    hero_btn_apple: "App Store",
    hero_btn_google: "Google Play",
    stat_modules: "Moduler",
    stat_platform: "Plattform",
    stat_founded: "Grundat",

    observe_tag: "Metodik",
    observe_h2_1: "Observera och",
    observe_h2_2: "Fånga",
    observe_p: "Gå igenom de olika komponenterna och avslöja processen fullt ut. Känn till de dolda delarna av processen som ofta tas för givna trots det plågsamma processlidandet.",
    observe_sub: "Lär dig och leta efter",
    feat1: "VÄRDESKAPANDE moment i en process",
    feat2: "Vad som stoppar en aktivitets fortsättning",
    feat3: "Flaskhalsar i processens fria flöde",
    feat4: "Om aktiviteterna är sömlöst utspridda",
    feat5: "De diskreta situationerna",
    feat6: "Enkelt att fånga osäkra ögonblick",
    feat7: "Objektiv processfångst genom jämförelser",
    feat8: "Historisk observation av processförändringar",

    devices_tag: "Plattformsoberoende",
    devices_h2_1: "Tillgänglig på alla",
    devices_h2_2: "Dina Enheter",
    devices_p1: "Var du än är kan lean-apparna i din hand hjälpa dig att forma processens verkliga karaktär genom att observera och synliggöra den — med bilder, ljud och videoinspelning, allt i din hand.",
    devices_p2: "Definiera styrkan i din monterings- eller affärsprocess genom detaljerad analys direkt till hands och arbeta med korrigerande åtgärder.",
    devices_p3: "PROJEKT hjälper till att koppla samman alla medlemmar och visar statusen var som helst, när som helst. Statusuppdateringar sker samtidigt överallt. Inget behov av möten eller uppföljningar —",
    devices_p3_em: " Du gör, du säger, du blir sedd.",

    rsv_tag: "Rätt Enkla Visuella Bilder",
    rsv_h2: "Ord är alltid bra.",
    rsv_p: "Alternativt gör de Rätt Enkla Visuella bilderna (RSV) ett intryck på sinnet. Detta hjälper och utlöser garanterat en reaktion från användaren för varje modul. Bilderna kopplar samman processverkligheten inför ögonen.",

    why_tag: "Metodik",
    why_h2: "Varför",
    why_p: "Lean-tänkande förändrar hur ditt företag verkar — eliminerar slöseri och fokuserar på det som verkligen skapar värde.",
    why_btn: "Se: Varför Lean Är Viktigt",

    feat_tag: "Vad Som Ingår",
    feat_h2_1: "Funktioner I",
    feat_h2_2: "Denna App",
    feat_desc: "Som projektledare för allt samarbete, stort som smått, ge människor möjlighet att arbeta i en teammiljö med hjälp av PROJEKT-modulen.",
    card1_title: "Gratis Provperiod",
    card1_p: "Börja utan kostnad. Utforska alla kärnfunktioner i 30 dagar innan du bestämmer dig.",
    card2_title: "Anpassade Moduler",
    card2_p: "Skräddarsy appens moduler efter din specifika bransch och arbetsflöde.",
    card3_title: "Projekt",
    card3_p: "Koppla samman alla teammedlemmar med statusuppdateringar i realtid, var som helst, när som helst.",
    card4_title: "Snabb Support",
    card4_p: "Få snabb expertassistans när du behöver vägledning i plattformen.",

    pricing_tag: "Planer",
    pricing_h2_1: "Gå Vidare Med",
    pricing_h2_2: "Handfast Kontroll",
    pricing_p: "Välj planen som passar dina behov för observation och analys.",
    plan_free: "Lean Gratis",
    period_trial: "/ 30 dagars provperiod",
    feat_img: "Bildfångst",
    feat_vid: "Videofångst",
    feat_extvid: "Utökad videofångst",
    feat_va: "Värdeskapande aktivitet",
    feat_nva: "Icke värdeskapande aktivitet",
    feat_ova: "Operationell värdeaktivitet",
    feat_unsafe: "Osäker Observation",
    feat_user: "Användarsektion",
    feat_compare: "Jämför",
    feat_projects: "Projekt",
    plan_silver: "Lean Silver",
    period_30: "/ 30 dagar",
    plan_gold: "Lean Guld",
    period_60: "/ 60 dagar",
    plan_popular: "Populär",
    plan_platinum: "Lean Platina",
    period_90: "/ 90 dagar",
    plan_monthly: "Lean Månadsvis",
    period_monthly: "/ månadsvis",

    about_tag: "Vilka Vi Är",
    about_h2_1: "Om",
    about_h2_2: "Oss",
    about_p: "Value-flow Sweden är ett konsultföretag som utvecklar appar för en effektivare industri, där vårt uppdrag är att våra kunder ska se sina möjligheter till förbättring. Grundat 2017 har företaget sedan dess arbetat för att uppnå högre effektivitet, säkrare produktion och mer jämlikhet inom industrin.",
    about_quote: "\"Till skillnad från många konsultföretag vill vi inte bara prata om vad du bör göra, utan istället hjälpa dig att göra det. Vi arbetar med att utveckla appar som använder modern teknik för att hjälpa våra kunder nå sina mål.\"",

    contact_tag: "Support",
    contact_h2_1: "Letar Du Efter",
    contact_h2_2: "Support?",
    contact_p: "Har du en fråga? Vi vill gärna höra från dig. Skicka ett meddelande så svarar vi så snart som möjligt.",
    contact_email_label: "E-posta Oss",
    contact_web_label: "Webbplats",
    contact_loc_label: "Plats",
    form_name: "Ditt Namn *",
    form_email: "E-postadress *",
    form_phone: "Telefonnummer",
    form_company: "Företag",
    form_subject: "Denna fråga handlar om...",
    form_opt0: "Välj ett ämne",
    form_opt1: "Registrering / Auktorisering",
    form_opt2: "Använda Applikationen",
    form_opt3: "Annat",
    form_msg_label: "Ditt Meddelande *",
    form_submit: "Skicka Ditt Meddelande",

    news_h3: "Håll dig uppdaterad med våra nyheter, idéer och uppdateringar",
    news_btn: "Prenumerera",

    footer_desc: "Lean Apps går igenom processkomponenter & förvandlar dem till en effektiv process.",
    footer_privacy: "Integritetspolicy",
    footer_terms: "Användarvillkor",
    footer_copy: "© 2018 value-flow.se — Alla Rättigheter Förbehållna"
  }
};

/* Flag + display-name shown ON the button itself.
   The button always shows the language you will SWITCH TO. */
window.LEAN_LANG_META = {
  en: { flag: "🇬🇧", label: "English" },
  sv: { flag: "🇸🇪", label: "Svenska" }
};